spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/restaurant
    username: postgres
    password: 1234



  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



server:
  port: 1111
  error:
    include-message: always

app:
  jwt:
    secret: java10
